[build]
  path="/dist"

[[edge_functions]]
  path = "/"
  function = "default-og"

[[edge_functions]]
  path = "/portfolio/*"
  function = "default-og"

[[edge_functions]]
  path = "/projects/*"
  function = "project-og"